# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "937137ad6bb47cdbb19f21e08a287d77"
name = "product-customizer-ui"
application_url = "https://product-customizer-ui.vercel.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://product-customizer-ui.vercel.app/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://product-customizer-ui.vercel.app/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders,read_draft_orders,read_files,write_files,write_order_edits,read_order_edits,read_orders,write_orders,read_products,write_products"


[auth]
redirect_urls = [
  "https://product-customizer-ui.vercel.app/auth/callback",
  "https://product-customizer-ui.vercel.app/auth/shopify/callback",
  "https://product-customizer-ui.vercel.app/api/auth/callback"
]

[pos]
embedded = false
